version: "3.9"
services:
  go:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app

  mysql:
    image: mysql:8.4.2
    platform: linux/arm64/v8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: minihr
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - ./docker/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf

  swagger:
    image: swaggerapi/swagger-ui:latest
    environment:
        PORT: "9000"
        SWAGGER_JSON: "/docs/openapi.yaml"
    ports:
      - "9000:9000"
    volumes:
      - ./docs:/docs
