version: "3.9"
services:
  go:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app

  mysql:
    image: mysql:latest
    platform: linux/arm64/v8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: minihr
      TZ: "Asia/Tokyo"
    volumes:
      - ./docker/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
